Partner review
Bateyjosue/todo-list-partner-review pull request #1
Opened 2022-08-17 06:32 UTC by Bateyjosue

## Samary

- Create a new empty repo.
- Copy my code from the "To Do list" project and commit it as one big chunk of code in a feature branch.
- Open a pull request.
- Ask my, partner, for a review.
- Share the pull request link with your partner.

2022-08-17 10:14 UTC, Alusp requested changes
### Hi @Bateyjosue,
### Good job so far!
There are some few issues that you still need to work on to go to the next project but you are almost there!



### Highlights
Your repo is professional ✅
Good summary description ✅
No Linter errors ✅
Required Changes ♻️
Check the comments under the review.

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise

2022-08-17 10:14 UTC, Alusp commented on README.md
> +
Nice Job on the Readme File :smiley:  but I think  it will be better if you add Acknowledgement and License Sections. The Acknowledgement Section is the best way to give credit to whoever helped you, it may be some tutors, bloggers, and designers.  

The License is good because, when you add it, it means that your project conforms with the MIT guide lines and this grant specific permissions on how your project is suppose to be used. :+1:

2022-08-17 10:14 UTC, Alusp commented on src/index.js
> +// });
Very good job here, but I think you should avoid using this type of comments in your code as they tend to mess up your code and I also think that you should put most of the methods in a separate js files and import them in the index.js file to obey the principle of clean code.

2022-08-17 10:14 UTC, Alusp commented on src/style.css
> +  border-bottom: 1px solid rgba(109, 105, 105, 0.767);
Good Job on the CSS, however, I think you can create a variable value for border-bottom and apply them to obey DRY principle

2022-08-17 10:31 UTC, Bateyjosue commented on .gitignore
> +dist/
Gotcha, Thanks I'll do it

2022-08-17 10:32 UTC, Bateyjosue commented on README.md
> +
Yeah, Acknowledgement okay.
 But do I have to add also license as long as I did not set my project any license?

2022-08-17 10:33 UTC, Bateyjosue commented on src/index.js
> +// });
Yeah, Nice Thanks

2022-08-17 10:35 UTC, Bateyjosue commented on src/style.css
> +  border-bottom: 1px solid rgba(109, 105, 105, 0.767);
Ah okay, gotcha. it is repeated many times. thanks, Man

2022-08-18 13:13 UTC, Alusp commented on README.md
> +
[Optional] I think License is needed when you want to have ownership of your project otherwise its okay to leave open

2022-08-18 13:48 UTC, Alusp approved these changes
Hi [@Bateyjosue](https://github.com/Bateyjosue) ✋,
Your project is complete! 🎯 🧠 💯

![clap](https://media3.giphy.com/media/YRuFixSNWFVcXaxpmX/giphy.gif)

There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

Highlights ⚡
✔️ Following Linters
✔️ Descriptive PR Title
✔️ Descriptive PR Summary

Optional suggestions 📂
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-08-18 14:45 UTC, merged

2023-02-06 18:21 UTC, Alusp commented on src/index.html
> +    </div>
I suggest you also follow HTML semantic here, as it makes the HTML more comprehensible by better defining the different sections and layout of web pages. It makes web pages more informative and adaptable, allowing browsers and search engines to better interpret content. :+1:

2023-02-06 18:22 UTC, Alusp commented on src/index.html
> +    </div>
I suggest you also follow HTML semantic here, as it makes the HTML more comprehensible by better defining the different sections and layout of web pages. It makes web pages more informative and adaptable, allowing browsers and search engines to better interpret content. :+1:

2023-02-07 15:01 UTC, Alusp commented on src/status.js
> +// export default updateStatus;
- [ ] Kindly remove these commented codes as they make your codebase look messy. It is among the coding best practices to remove unnecessary commented codes. :+1:

2023-02-07 15:04 UTC, Alusp commented on src/status.js
> +// export default updateStatus;
- [ ] Kindly remove these commented codes as they make your codebase look messy. It is among the coding best practices to remove unnecessary commented codes. :+1:

2023-02-07 15:16 UTC, Alusp commented on src/index.html
> +    </div>
- [ ] Good Job So far, I suggest you also follow HTML semantic in your index.html file like having a section, heading, main tags respectively,  as it makes the HTML more comprehensible by better defining the different sections and layout of web pages. It makes web pages more informative and adaptable, allowing browsers and search engines to better interpret content. :+1: 

HINT:
1.  Please change the div tag with class name = "todo-list-container" to section tag
2. Change p tag to heading like h2

2023-04-17 10:08 UTC, Alusp reviewed
Hi @Bateyjosue,

Good job so far!
There are some few issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️♻️♻️

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

### Highlights
Your repo is professional ✅
Good summary description ✅
No Linter errors ✅


Check the comments under the review.

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise

2023-04-17 10:08 UTC, Alusp commented on src/index.html
> +    </div>
- [ ] Please follow the HTML semantics to make your code more readable for screen readers and it will also help you to improve the accessibility. Please use `main` tag to wrap your body content instead of `div`, because `div` tags are not part of HTML semantics. It is only used for styling purposes.

2023-04-17 10:08 UTC, Alusp commented on src/index.js
> +});
- `[Optional]` : Please use the `insertAdjacentHTML` DOM method instead of `innerHTML` method for adding the dynamic HTML content through JavaScript, because `innerHTML` method have `security` issues, while working on full stack project. for example like `SQL-Injection` by someone intentionally or unintentionally which can delete the data from your database.

2023-04-17 10:08 UTC, Alusp commented on src/status.js
> +}
- Please follow the `DRY` principle because as I can see that you are  repeating method
  > this.task.updateTask()

- Please put above line of code just after the if and else statement to not repeat yourself again and again.